language: node_js
node_js:
  - "8"

sudo: false

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test

jobs:
  include:
    - script: cp .env.example .env
    - stage: build
      script: npm install
    - stage: test
      script: npm run lint
      script: npm run test
