language: node_js
node_js:
  - "8"

sudo: false

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test

jobs:
  include:
    - stage: test
      script: npm run lint
      script: cp .env.example .env && npm run test
