language: node_js
node_js:
  - "8"

sudo: false

cache:
  directories:
    - "node_modules"

stages:
  - test

jobs:
  include:
    - stage: test
      name: "Linting"
      script: npm run lint
      name: "Unit test"
      script:
        - cp .env.example .env
        - npm run test
